# Railway.app deployment configuration
[build]
  builder = "nixpacks"

[deploy]
  healthcheckPath = "/api/health"
  healthcheckTimeout = 60
  restartPolicyType = "always"
  startCommand = "gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 2"

[variables]
  PYTHONPATH = "/app/src"