# Render.com deployment configuration
services:
  - type: web
    name: european-travel-planner
    runtime: docker
    plan: free
    region: oregon
    buildCommand: ""
    startCommand: ""
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: GOOGLE_MAPS_API_KEY
        sync: false
      - key: OPENROUTE_API_KEY
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: travel-planner-redis
          property: connectionString

  - type: redis
    name: travel-planner-redis
    plan: free
    region: oregon