# Render.com deployment configuration
services:
  - type: web
    name: european-travel-planner
    runtime: docker
    plan: free
    region: oregon
    healthCheckPath: /api/health
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: PORT
        value: 8000